//Language: Spanish
//Translators: softwarerero

var es = {
  add: "agregar",
  and: "y",
  back: "atrás",
  changePassword: "Cambiar contraseña",
  choosePassword: "Eligir contraseña",
  clickAgree: "Al hacer clic en Sucribir apruebas la",
  configure: "Disposición",
  createAccount: "Crear cuenta",
  currentPassword: "Contraseña actual",
  dontHaveAnAccount: "No tienes una cuenta?",
  email: "Email",
  emailAddress: "Dirección de email",
  emailResetLink: "Reiniciar email",
  forgotPassword: "Olvidó su contraseña?",
  ifYouAlreadyHaveAnAccount: "Si ya tiene una cuenta",
  newPassword: "Nueva contraseña",
  newPasswordAgain: "Nueva contraseña (repetir)",
  optional: "Opcional",
  OR: "O",
  password: "Contraseña",
  passwordAgain: "Contraseña (repetir)",
  privacyPolicy: "Póliza de Privacidad",
  remove: "remover",
  resetYourPassword: "Resetear tu contraseña",
  setPassword: "Definir contraseña",
  sign: "Ingresar",
  signIn: "Entrar",
  signin: "entrar",
  signOut: "Salir",
  signUp: "Registrarse",
  signupCode: "Código de registro",
  signUpWithYourEmailAddress: "Registrarse con tu email",
  terms: "Términos de uso",
  updateYourPassword: "Actualizar tu contraseña",
  username: "Usuario",
  usernameOrEmail: "Usuario o email",
  "with": "con",
  info: {
    emailSent: "Email enviado",
    emailVerified: "Email verificado",
    passwordChanged: "Contraseña cambiada",
    passwordReset: "Resetear contraseña"
  },
  error: {
    emailRequired: "El email es requerido.",
    minChar: "7 caracteres mínimo.",
    pwdsDontMatch: "Las contraseñas no coinciden",
    pwOneDigit: "mínimo un dígito.",
    pwOneLetter: "mínimo una letra.",
    signInRequired: "Debes iniciar sesión para hacer eso.",
    signupCodeIncorrect: "El código de suscripción no coincide.",
    signupCodeRequired: "Se requiere el código de suscripción.",
    usernameIsEmail: "El usuario no puede ser el email.",
    usernameRequired: "Se requiere un usuario.",
    accounts: {
      "Email already exists.": "El email ya existe.",
      "Email doesn't match the criteria.": "El email no coincide con los criterios.",
      "User validation failed": "No se ha podido validar el usuario",
      "Username already exists.": "El usuario ya existe.",
      "You've been logged out by the server. Please log in again.": "Has sido desconectado por el servidor. Por favor ingresa de nuevo.",
      "Your session has expired. Please log in again.": "Tu sesión ha expirado. Por favor ingresa de nuevo.",
      "Incorrect password": "Contraseña inválida",
      "Must be logged in": "Debes ingresar",
      "Need to set a username or email": "Tienes que especificar un usuario o un email",
      "Signups forbidden": "Registro prohibido",
      "Token expired": "Token expirado",
      "Token has invalid email address": "Token contiene un email inválido",
      "User has no password set": "Usuario no tiene contraseña",
      "User not found": "Usuario no encontrado",
      "Verify email link expired": "El enlace para verificar el email ha expirado",
      "Verify email link is for unknown address": "El enlace para verificar el email contiene una dirección desconocida"
    }
  }
};

T9n.map("es", es);
